[package]
name = "redirector"
version = "0.3.0"
authors = ["Charles Tabor <chastabor@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.7"
lazy_static = "1.4.0"
tokio = { version = "0.2.5", features = ["full"] }
