[package]
name = "health"
version = "0.1.0"
authors = ["Charles Tabor <chastabor@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
lazy_static = "1.4.0"
